
services:
  - type: web
    name: laravel12-app
    env: docker
    plan: free
    repo: https://github.com/616ZaikoSKZ/laravel3.git
    region: oregon
    buildCommand: "echo 'Dockerfile already handles build'"
    startCommand: "echo 'Dockerfile already handles start'"
